### ISSUE TITLE
Problème sur le nombre de classes

### ISSUE THREAD

**Issue by ericmermet** [paristimemachine/ptm4qgis-morphal#1]
Lorsque l'on produit un calcul d'orientation, par exemple sur un step de 5°, on devrait avoir 180 / 5 classes, soit 36.
Or on observe 37 classes, une est systématiquement mise pour les orientations de 180 uniquement.
Pour un step de 10, on a 19 classes.

**Comment by ericgrosso** [comment]
Problème identifié :

https://github.com/paristimemachine/ptm4qgis-morphal/blob/c9528063e32d21012cb9eaa8d50d564a9f45550e/morphal/core/morphal_geometry_utils.py#L364

round(89.9999,3)=90
round(179.9999,3)=180
